[workspace]
members = [
  "migration",
  "entity",
  "lib",
  "jobs",
]

[profile.release]
strip = true
lto = true
codegen-units = 1

[workspace.dependencies]
anyhow = { version = "1.0.69", default-features = false, features = ["std"] }
chrono = { version = "0.4.23", default-features = false }
config = { version = "0.13.3", default-features = false, features = ["toml"] }
entity = { version = "0.1.0", path = "./entity" }
hmac = { version = "0.12.1", default-features = false }
jwt = { version = "0.16.0", default-features = false }
lib = { version = "0.1.0", path = "./lib" }
poem = { version = "1.3.54", default-features = false, features = ["server"] }
poem-ext = { version = "0.4.1", default-features = false, features = ["sea-orm"] }
poem-openapi = { version = "2.0.25", default-features = false, features = ["swagger-ui", "redoc", "uuid", "chrono"] }
sea-orm = { version = "0.11.0", default-features = false, features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "with-uuid", "with-chrono", "postgres-array"] }
serde = { version = "1.0.152", default-features = false, features = ["derive"] }
sha2 = { version = "0.10.6", default-features = false }
tokio = { version = "1.25.0", default-features = false, features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1.37", default-features = false }
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["fmt", "ansi"] }
uuid = { version = "1.3.0", default-features = false, features = ["v4", "fast-rng"] }
