[workspace]
members = [
  "migration",
  "entity",
  "lib",
  # "jobs",
  "challenges",
]

[profile.release]
strip = true
lto = true
codegen-units = 1

[workspace.dependencies]
anyhow = { version = "1.0.69", default-features = false, features = ["std"] }
chrono = { version = "0.4.23", default-features = false }
config = { version = "0.13.3", default-features = false, features = ["toml"] }
entity = { version = "0.1.0", path = "./entity" }
fnct = { version = "0.2.0", default-features = false }
hmac = { version = "0.12.1", default-features = false }
itertools = { version = "0.10.5", default-features = false, features = ["use_std"] }
jwt = { version = "0.16.0", default-features = false }
lib = { version = "0.1.0", path = "./lib" }
poem = { version = "1.3.54", default-features = false, features = ["server"] }
poem-ext = { version = "0.5.2", default-features = false, features = ["sea-orm"] }
poem-openapi = { version = "2.0.25", default-features = false, features = ["swagger-ui", "redoc", "uuid", "chrono"] }
redis = { version = "0.22.3", default-features = false, features = ["tokio-comp", "connection-manager"] }
reqwest = { version = "0.11.14", default-features = false, features = ["rustls-tls", "json"] }
sea-orm = { version = "0.11.2", default-features = false, features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "with-uuid", "with-chrono", "postgres-array"] }
serde = { version = "1.0.152", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.94", default-features = false }
sha2 = { version = "0.10.6", default-features = false }
thiserror = { version = "1.0.40", default-features = false }
tokio = { version = "1.27.0", default-features = false, features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1.37", default-features = false }
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["fmt", "ansi"] }
url = { version =  "2.3.1", default-features = false, features = ["serde"] }
uuid = { version = "1.3.0", default-features = false, features = ["v4", "fast-rng", "serde"] }
