[workspace]
members = [
  "migration",
  "entity",
  "lib",
  "jobs",
]

[workspace.dependencies]
anyhow = { version = "1.0.69", default-features = false, features = ["std"] }
config = { version = "0.13.3", default-features = false, features = ["toml"] }
entity = { version = "0.1.0", path = "./entity" }
lib = { version = "0.1.0", path = "./lib" }
poem = { version = "1.3.54", default-features = false, features = ["server"] }
poem-openapi = { version = "2.0.25", default-features = false, features = ["swagger-ui", "redoc", "uuid"] }
sea-orm = { version = "0.10.7", default-features = false, features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "with-uuid", "with-chrono", "postgres-array"] }
serde = { version = "1.0.152", default-features = false, features = ["derive"] }
tokio = { version = "1.25.0", default-features = false, features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1.37", default-features = false }
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["fmt", "ansi"] }
uuid = { version = "1.3.0", default-features = false, features = ["v4", "fast-rng"] }
