jwt_secret = "changeme"
internal_jwt_ttl = 10  # seconds
cache_ttl = 600  # seconds

[database]
url = "postgres://academy:academy@localhost/academy"
connect_timeout = 5  # seconds

[redis]
auth = "redis://localhost:6379/0"
skills = "redis://localhost:6379/1"
shop = "redis://localhost:6379/2"
jobs = "redis://localhost:6379/3"
events = "redis://localhost:6379/4"
challenges = "redis://localhost:6379/5"

[services]
auth = "http://localhost:8000"
skills = "http://localhost:8001"
shop = "http://localhost:8002"
jobs = "http://localhost:8003"
events = "http://localhost:8004"
challenges = "http://localhost:8005"

[auth]
host = "127.0.0.1"
port = 8000

[skills]
host = "127.0.0.1"
port = 8001

[shop]
host = "127.0.0.1"
port = 8002

[jobs]
host = "127.0.0.1"
port = 8003

[events]
host = "127.0.0.1"
port = 8004

[challenges]
host = "127.0.0.1"
port = 8005

[challenges.multiple_choice_questions]
timeout_incr = 10  # seconds
