jwt_secret = "changeme"
internal_jwt_ttl = 10  # seconds
cache_ttl = 600  # seconds

[database]
url = "postgres://academy:academy@database:5432/academy"
connect_timeout = 5  # seconds

[redis]
auth = "redis://redis:6379/0"
skills = "redis://redis:6379/1"
shop = "redis://redis:6379/2"
jobs = "redis://redis:6379/3"
events = "redis://redis:6379/4"
challenges = "redis://redis:6379/5"

[services]
auth = "http://auth:8000"
skills = "http://skills:8000"
shop = "http://shop:8000"
jobs = "http://jobs:8000"
events = "http://events:8000"
challenges = "http://challenges:8000"

[auth]
host = "0.0.0.0"
port = 8000
server = "/"

[skills]
host = "0.0.0.0"
port = 8000
server = "/"

[shop]
host = "0.0.0.0"
port = 8000
server = "/"

[jobs]
host = "0.0.0.0"
port = 8000
server = "/"

[events]
host = "0.0.0.0"
port = 8000
server = "/"

[challenges]
host = "0.0.0.0"
port = 8000
server = "/"

# [challenges.sentry]
# dsn = ""

[challenges.quizzes]
min_level = 5
max_xp = 5
max_coins = 0
ban_days = [3, 7, 30]

[challenges.multiple_choice_questions]
timeout = 2  # seconds
hearts = 1
creator_coins = 1

[challenges.questions]
timeout = 2  # seconds
hearts = 1
creator_coins = 1

[challenges.matchings]
timeout = 2  # seconds
hearts = 1
creator_coins = 1

[challenges.coding_challenges]
sandkasten_url = "http://sandkasten"
max_concurrency = 4
timeout = 10  # seconds
hearts = 2
creator_coins = 10
