jwt_secret = "changeme"
internal_jwt_ttl = 10

[database]
url = "postgres://academy:academy@localhost/academy"
connect_timeout = 5

[redis]
auth = "redis://localhost:6379/0"
skills = "redis://localhost:6379/1"
shop = "redis://localhost:6379/2"
jobs = "redis://localhost:6379/3"
events = "redis://localhost:6379/4"

[services]
auth = "http://localhost:8000"
skills = "http://localhost:8001"
shop = "http://localhost:8002"
jobs = "http://localhost:8003"
events = "http://localhost:8004"

[auth]
host = "127.0.0.1"
port = 8000

[skills]
host = "127.0.0.1"
port = 8001

[shop]
host = "127.0.0.1"
port = 8002

[jobs]
host = "127.0.0.1"
port = 8003

[events]
host = "127.0.0.1"
port = 8004
