//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "challenges_cloze_attempts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub cloze_id: Uuid,
    pub user_id: Uuid,
    pub timestamp: DateTime,
    pub correct: i32,
    pub total: i32,
    pub solved: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::challenges_clozes::Entity",
        from = "Column::ClozeId",
        to = "super::challenges_clozes::Column::SubtaskId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ChallengesClozes,
}

impl Related<super::challenges_clozes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengesClozes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
