//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "challenges_subtasks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub task_id: Uuid,
    pub creator: Uuid,
    pub creation_timestamp: DateTime,
    pub xp: i64,
    pub coins: i64,
    pub fee: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::challenges_coding_challenges::Entity")]
    ChallengesCodingChallenges,
    #[sea_orm(has_many = "super::challenges_multiple_choice_quizes::Entity")]
    ChallengesMultipleChoiceQuizes,
    #[sea_orm(
        belongs_to = "super::challenges_tasks::Entity",
        from = "Column::TaskId",
        to = "super::challenges_tasks::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ChallengesTasks,
}

impl Related<super::challenges_coding_challenges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengesCodingChallenges.def()
    }
}

impl Related<super::challenges_multiple_choice_quizes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengesMultipleChoiceQuizes.def()
    }
}

impl Related<super::challenges_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengesTasks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
