//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "challenges_cloze_blanks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub cloze_id: Uuid,
    pub placeholder: i32,
    #[sea_orm(column_type = "Text")]
    pub answer: String,
    pub synonyms: Vec<String>,
    pub correct_option_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::challenges_clozes::Entity",
        from = "Column::ClozeId",
        to = "super::challenges_clozes::Column::SubtaskId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ChallengesClozes,
    #[sea_orm(
        belongs_to = "super::challenges_cloze_options::Entity",
        from = "Column::CorrectOptionId",
        to = "super::challenges_cloze_options::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    ChallengesClozeOptions,
}

impl Related<super::challenges_clozes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengesClozes.def()
    }
}

impl Related<super::challenges_cloze_options::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengesClozeOptions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
