//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "challenges_clozes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub subtask_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub case_sensitive: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::challenges_cloze_options::Entity")]
    ChallengesClozeOptions,
    #[sea_orm(has_many = "super::challenges_cloze_blanks::Entity")]
    ChallengesClozeBlanks,
    #[sea_orm(has_many = "super::challenges_cloze_attempts::Entity")]
    ChallengesClozeAttempts,
    #[sea_orm(
        belongs_to = "super::challenges_subtasks::Entity",
        from = "Column::SubtaskId",
        to = "super::challenges_subtasks::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ChallengesSubtasks,
}

impl Related<super::challenges_cloze_options::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengesClozeOptions.def()
    }
}

impl Related<super::challenges_cloze_blanks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengesClozeBlanks.def()
    }
}

impl Related<super::challenges_cloze_attempts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengesClozeAttempts.def()
    }
}

impl Related<super::challenges_subtasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengesSubtasks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
