//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "challenges_coding_challenge_example")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub challenge_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub input: String,
    #[sea_orm(column_type = "Text")]
    pub output: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub explanation: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::challenges_coding_challenges::Entity",
        from = "Column::ChallengeId",
        to = "super::challenges_coding_challenges::Column::SubtaskId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ChallengesCodingChallenges,
}

impl Related<super::challenges_coding_challenges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengesCodingChallenges.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
