//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub mod prelude;

pub mod challenges_ban;
pub mod challenges_challenge_categories;
pub mod challenges_challenges;
pub mod challenges_coding_challenge_result;
pub mod challenges_coding_challenge_submissions;
pub mod challenges_coding_challenges;
pub mod challenges_course_tasks;
pub mod challenges_matching_attempts;
pub mod challenges_matchings;
pub mod challenges_multiple_choice_attempts;
pub mod challenges_multiple_choice_quizes;
pub mod challenges_question_attempts;
pub mod challenges_questions;
pub mod challenges_subtask_reports;
pub mod challenges_subtasks;
pub mod challenges_tasks;
pub mod challenges_user_subtasks;
pub mod sea_orm_active_enums;
