//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub mod prelude;

pub mod challenges_challenge_categories;
pub mod challenges_challenges;
pub mod challenges_coding_challenge_example;
pub mod challenges_coding_challenges;
pub mod challenges_course_tasks;
pub mod challenges_multiple_choice_quizes;
pub mod challenges_subtasks;
pub mod challenges_tasks;
pub mod jobs_companies;
pub mod jobs_jobs;
pub mod jobs_skill_requirements;
pub mod sea_orm_active_enums;
