//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::{
    challenges_challenge_categories::Entity as ChallengesChallengeCategories,
    challenges_challenges::Entity as ChallengesChallenges,
    challenges_coding_challenge_result::Entity as ChallengesCodingChallengeResult,
    challenges_coding_challenge_submissions::Entity as ChallengesCodingChallengeSubmissions,
    challenges_coding_challenges::Entity as ChallengesCodingChallenges,
    challenges_course_tasks::Entity as ChallengesCourseTasks,
    challenges_multiple_choice_attempts::Entity as ChallengesMultipleChoiceAttempts,
    challenges_multiple_choice_quizes::Entity as ChallengesMultipleChoiceQuizes,
    challenges_subtasks::Entity as ChallengesSubtasks, challenges_tasks::Entity as ChallengesTasks,
};
