//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::challenges_challenge_categories::Entity as ChallengesChallengeCategories;
pub use super::challenges_challenges::Entity as ChallengesChallenges;
pub use super::challenges_coding_challenge_example::Entity as ChallengesCodingChallengeExample;
pub use super::challenges_coding_challenges::Entity as ChallengesCodingChallenges;
pub use super::challenges_multiple_choice_quizes::Entity as ChallengesMultipleChoiceQuizes;
pub use super::challenges_skill_tasks::Entity as ChallengesSkillTasks;
pub use super::challenges_subtasks::Entity as ChallengesSubtasks;
pub use super::challenges_tasks::Entity as ChallengesTasks;
pub use super::jobs_companies::Entity as JobsCompanies;
pub use super::jobs_jobs::Entity as JobsJobs;
pub use super::jobs_skill_requirements::Entity as JobsSkillRequirements;
