//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

pub use super::jobs_companies::Entity as JobsCompanies;
pub use super::jobs_jobs::Entity as JobsJobs;
pub use super::jobs_skill_requirements::Entity as JobsSkillRequirements;
