//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Copy,
    poem_openapi::Enum,
    serde::Serialize,
    serde::Deserialize,
)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
#[oai(rename_all = "SCREAMING_SNAKE_CASE")]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "challenges_ban_action"
)]
pub enum ChallengesBanAction {
    #[sea_orm(string_value = "create")]
    Create,
    #[sea_orm(string_value = "report")]
    Report,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Copy,
    poem_openapi::Enum,
    serde::Serialize,
    serde::Deserialize,
)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
#[oai(rename_all = "SCREAMING_SNAKE_CASE")]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "challenges_rating")]
pub enum ChallengesRating {
    #[sea_orm(string_value = "negative")]
    Negative,
    #[sea_orm(string_value = "neutral")]
    Neutral,
    #[sea_orm(string_value = "positive")]
    Positive,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Copy,
    poem_openapi::Enum,
    serde::Serialize,
    serde::Deserialize,
)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
#[oai(rename_all = "SCREAMING_SNAKE_CASE")]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "challenges_report_reason"
)]
pub enum ChallengesReportReason {
    #[sea_orm(string_value = "abuse")]
    Abuse,
    #[sea_orm(string_value = "dislike")]
    Dislike,
    #[sea_orm(string_value = "other")]
    Other,
    #[sea_orm(string_value = "unrelated_skill")]
    UnrelatedSkill,
    #[sea_orm(string_value = "wrong")]
    Wrong,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Copy,
    poem_openapi::Enum,
    serde::Serialize,
    serde::Deserialize,
)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
#[oai(rename_all = "SCREAMING_SNAKE_CASE")]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "challenges_verdict")]
pub enum ChallengesVerdict {
    #[sea_orm(string_value = "compilation_error")]
    CompilationError,
    #[sea_orm(string_value = "invalid_output_format")]
    InvalidOutputFormat,
    #[sea_orm(string_value = "memory_limit_exceeded")]
    MemoryLimitExceeded,
    #[sea_orm(string_value = "no_output")]
    NoOutput,
    #[sea_orm(string_value = "ok")]
    Ok,
    #[sea_orm(string_value = "pre_check_failed")]
    PreCheckFailed,
    #[sea_orm(string_value = "runtime_error")]
    RuntimeError,
    #[sea_orm(string_value = "time_limit_exceeded")]
    TimeLimitExceeded,
    #[sea_orm(string_value = "wrong_answer")]
    WrongAnswer,
}
