//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Copy,
    poem_openapi::Enum,
    serde::Serialize,
    serde::Deserialize,
)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
#[oai(rename_all = "SCREAMING_SNAKE_CASE")]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "challenges_verdict")]
pub enum ChallengesVerdict {
    #[sea_orm(string_value = "compilation_error")]
    CompilationError,
    #[sea_orm(string_value = "invalid_output_format")]
    InvalidOutputFormat,
    #[sea_orm(string_value = "memory_limit_exceeded")]
    MemoryLimitExceeded,
    #[sea_orm(string_value = "no_output")]
    NoOutput,
    #[sea_orm(string_value = "ok")]
    Ok,
    #[sea_orm(string_value = "runtime_error")]
    RuntimeError,
    #[sea_orm(string_value = "time_limit_exceeded")]
    TimeLimitExceeded,
    #[sea_orm(string_value = "wrong_answer")]
    WrongAnswer,
}
